name: babosthapotro
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.3
  flutter_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  dio: ^5.9.0
  retrofit: ^4.9.1
  shared_preferences: ^2.5.4
  go_router: ^17.0.1
  gap: ^3.0.1
  url_launcher: ^6.3.2
  flutter_inappwebview: ^6.1.5
  pinput: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.10.4
  riverpod_generator: ^3.0.3
  freezed: ^3.2.3
  json_serializable: ^6.11.2
  retrofit_generator: ^10.2.0
  flutter_launcher_icons: ^0.14.4


flutter:

  uses-material-design: true

  assets:
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/icon.png"

